Repository jetstack/tarmak, pull requests merged in 2018-12, with the labels that each got.

#644 Upgrade Kubernetes to 1.11.5
  CHANGELOG.md
  pkg/apis/cluster/v1alpha1/defaults.go
  puppet/modules/tarmak/Makefile
Labels: approved, cherrypick-approved, dco-signoff: yes, lgtm, release-note, size/XS

#645 Automated cherry pick of #644
  CHANGELOG.md
  pkg/apis/cluster/v1alpha1/defaults.go
  puppet/modules/tarmak/Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#646 Fix centos aws cli again
  packer/amazon/centos-puppet-agent-latest-kernel.json
  packer/amazon/centos-puppet-agent.json
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#439 Expose feature flags
  docs/generated/reference/output/api-docs.html
  docs/generated/reference/output/navData.js
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/puppet/puppet.go
  pkg/puppet/puppet_test.go
  pkg/tarmak/utils/maps.go
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/manifests/controller_manager.pp
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/manifests/proxy.pp
  puppet/modules/kubernetes/manifests/scheduler.pp
  puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
  puppet/modules/kubernetes/spec/classes/controller_manager_spec.rb
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/spec/classes/proxy_spec.rb
  puppet/modules/kubernetes/spec/classes/scheduler_spec.rb
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
  puppet/modules/kubernetes/templates/kube-controller-manager.service.erb
  puppet/modules/kubernetes/templates/kube-proxy-config.yaml.erb
  puppet/modules/kubernetes/templates/kube-proxy.service.erb
  puppet/modules/kubernetes/templates/kube-scheduler.service.erb
  puppet/modules/kubernetes/templates/kubelet-config.yaml.erb
  puppet/modules/kubernetes/templates/kubelet.service.erb
  terraform/amazon/templates/modules.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#538 Correctly mount nvme drives for etcd instances
  puppet/modules/aws_ebs/manifests/mount.pp
  puppet/modules/aws_ebs/spec/defines/mount_spec.rb
  puppet/modules/aws_ebs/templates/ensure-volume-formatted.service.erb
  puppet/modules/tarmak/manifests/etcd.pp
  puppet/modules/tarmak/manifests/vault.pp
  puppet/modules/tarmak/spec/spec_helper.rb
Labels: approved, cherrypick-approved, dco-signoff: yes, lgtm, release-note, size/M

#651 Automated cherry pick of #646
  packer/amazon/centos-puppet-agent-latest-kernel.json
  packer/amazon/centos-puppet-agent.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#650 Automated cherry pick of #538
  puppet/modules/aws_ebs/manifests/mount.pp
  puppet/modules/aws_ebs/spec/defines/mount_spec.rb
  puppet/modules/aws_ebs/templates/ensure-volume-formatted.service.erb
  puppet/modules/tarmak/manifests/etcd.pp
  puppet/modules/tarmak/manifests/vault.pp
  puppet/modules/tarmak/spec/spec_helper.rb
Labels: approved, dco-signoff: yes, lgtm, size/M

#649 Hardcode centos release
  packer/amazon/centos-puppet-agent-latest-kernel.json
  packer/amazon/centos-puppet-agent.json
  packer/amazon/cleanup.sh
  packer/amazon/configure_for_tarmak.sh
  packer/amazon/configure_latest_kernel.sh
Labels: approved, cherrypick-approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#652 Override entire kubeconfig if errors
  pkg/tarmak/kubectl/kubectl.go
Labels: approved, cherrypick-approved, dco-signoff: yes, lgtm, release-note, size/L

#653 Automated cherry pick of #652
  pkg/tarmak/kubectl/kubectl.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#654 Automated cherry pick of #649
  packer/amazon/centos-puppet-agent-latest-kernel.json
  packer/amazon/centos-puppet-agent.json
  packer/amazon/cleanup.sh
  packer/amazon/configure_for_tarmak.sh
  packer/amazon/configure_latest_kernel.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#656 Add owners file
  docs/OWNERS
  puppet/OWNERS
  terraform/OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, retest-not-required-docs-only, size/S

#658 Fix latest kernel packer image
  hack/update-reference-docs.sh
  packer/amazon/configure_latest_kernel.sh
Labels: approved, cherrypick-candidate, dco-signoff: yes, lgtm, release-note, size/XS

#660 Fix error when running kube commands with public API
  pkg/tarmak/kubectl/kubectl.go
Labels: approved, cherrypick-approved, dco-signoff: yes, kind/documentation, lgtm, release-note, size/XS

#662 Automated cherry pick of #660 #658
  hack/update-reference-docs.sh
  packer/amazon/configure_latest_kernel.sh
  pkg/tarmak/kubectl/kubectl.go
Labels: approved, approved-for-milestone, cherrypick-approved, dco-signoff: yes, do-not-merge/cherry-pick-not-approved, lgtm, release-note, size/S

#643 Adds management of ssh_known_hosts file proposal
  docs/proposals/ssh-known_hosts.rst
  docs/spelling_wordlist.txt
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note, size/L
