Repository jetstack/tarmak, pull requests merged in 2018-09, with the labels that each got.

#443 Copy docker files even when start fails
  docs/Makefile
Labels: approved, lgtm, release-note-none, size/XS

#486 Applies hot fix for class loop in airworthy module
  puppet/hieradata/role/etcd.yaml
Labels: approved, lgtm, release-note-none, size/XS

#489 Add contribution guide
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, retest-not-required-docs-only, size/M

#488 Fix role specs
  puppet/Makefile
  puppet/modules/aws_ebs/functions/disks.pp
  puppet/spec/hosts/etcd_spec.rb
  puppet/spec/hosts/master_spec.rb
  puppet/spec/hosts/worker_spec.rb
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#492 Add option to enable API Server ELB access logs
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/v1alpha1/zz_generated.defaults.go
  pkg/apis/tarmak/v1alpha1/zz_generated.defaults.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/role/role.go
  terraform/amazon/modules/kubernetes/inputs.tf
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/role_elb.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#491 Upgrade heapster
  puppet/modules/kubernetes_addons/manifests/heapster.pp
  puppet/modules/kubernetes_addons/manifests/params.pp
  puppet/modules/kubernetes_addons/templates/heapster-deployment.yaml.erb
  puppet/modules/kubernetes_addons/templates/heapster-rbac.yaml.erb
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#487 Add metrics server
  puppet/hieradata/role/master.yaml
  puppet/modules/kubernetes_addons/manifests/metrics_server.pp
  puppet/modules/kubernetes_addons/spec/classes/metrics_server_spec.rb
  puppet/modules/kubernetes_addons/templates/metrics-server-rbac.yaml.erb
  puppet/modules/kubernetes_addons/templates/metrics-server.yaml.erb
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#495 Add Terraform debug shell error when binary version is incompatible
  Gopkg.lock
  pkg/tarmak/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#478 Validate Jenkins as a valid instance pool for hub
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/cluster/cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#498 Download backinator binary in consul puppet module
  puppet/modules/consul/manifests/init.pp
  puppet/modules/consul/manifests/install.pp
  puppet/modules/consul/manifests/params.pp
  puppet/modules/consul/spec/classes/install_spec.rb
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#502 Restart Consul on failure
  puppet/modules/consul/templates/consul.service.erb
  terraform/amazon/modules/vault/templates/vault_user_data.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#456 Expose scale down utilization threshold
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/v1alpha1/zz_generated.defaults.go
  pkg/apis/tarmak/v1alpha1/zz_generated.defaults.go
  pkg/puppet/puppet.go
  pkg/tarmak/cluster/cluster.go
  puppet/modules/kubernetes_addons/manifests/cluster_autoscaler.pp
  puppet/modules/kubernetes_addons/templates/cluster-autoscaler-deployment.yaml.erb
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#356 Forwarding Interrupt to processes
  cmd/tarmak/cmd/cluster_apply.go
  cmd/tarmak/cmd/cluster_debug_terraform_shell.go
  cmd/tarmak/cmd/cluster_destroy.go
  cmd/tarmak/cmd/cluster_images_build.go
  cmd/tarmak/cmd/cluster_plan.go
  cmd/tarmak/cmd/terraform.go
  pkg/packer/image.go
  pkg/packer/packer.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/tarmak_test.go
  pkg/tarmak/terraform.go
  pkg/tarmak/utils/context.go
  pkg/terraform/passthrough.go
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#510 Restart bastion etcd and wing-server on failure
  terraform/amazon/modules/bastion/templates/bastion_user_data.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#503 Upgrade calico to 3.1.3
  CHANGELOG.md
  puppet/modules/calico/manifests/node.pp
  puppet/modules/calico/manifests/policy_controller.pp
  puppet/modules/calico/templates/node-daemonset.yaml.erb
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#505 KMS encrypt terraform remote state
  pkg/tarmak/provider/amazon/amazon.go
  pkg/tarmak/provider/amazon/amazon_test.go
  pkg/tarmak/provider/amazon/key_pair.go
  pkg/tarmak/provider/amazon/key_pair_test.go
  pkg/tarmak/provider/amazon/route53.go
  pkg/tarmak/provider/amazon/tf_remote_state.go
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#445 Spire proposal/testing results doc
  docs/proposals/spiffe-spire-integration.rst
  docs/spelling_wordlist.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#525 Adds hot fix to remote state variable order
  pkg/tarmak/provider/amazon/tf_remote_state.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#524 Fix API ELBs SSL healthcheck endpoint
  terraform/amazon/templates/instance_pools/role_elb.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#521 Verify if terraform plans containing the destruction of EBS volumes
  pkg/terraform/plan/plan.go
  pkg/terraform/plan/plan_test.go
  pkg/terraform/plan/test_data/create.plan
  pkg/terraform/plan/test_data/destroy.plan
  pkg/terraform/plan/test_data/destroy_non_ebs.plan
  pkg/terraform/plan/test_data/destroy_non_module_ebs.plan
  pkg/terraform/plan/test_data/modify.plan
  pkg/terraform/plan/test_data/my.plan
  pkg/terraform/plan/test_data/nochanges.plan
  pkg/terraform/plan/test_data/recreate.plan
  pkg/terraform/plan/test_data/tainted.plan
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#526 Ensure validate/verify is run during a debug shell
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/provider/amazon/amazon.go
  pkg/tarmak/provider/amazon/key_pair.go
  pkg/tarmak/provider/amazon/key_pair_test.go
  pkg/tarmak/provider/amazon/tf_remote_state.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#530 Fix verify of multicluster
  pkg/tarmak/provider/amazon/tf_remote_state.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#532 Adds ci to docs Makefile
  docs/Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#512 Use healthy vault tunnel and implement constant backoff
  pkg/tarmak/environment/bastion.go
  pkg/tarmak/vault/vault.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#536 Increase time to try and get vault tunnel connection
  pkg/tarmak/vault/vault.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#522 Adds force-unlock terraform command
  cmd/tarmak/cmd/cluster_force-unlock.go
  pkg/tarmak/provider/amazon/amazon.go
  pkg/tarmak/terraform.go
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#542 Update Tarmak docs section on PSP
  docs/user-guide.rst
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#531 Add optional EBS encryption and protect EBS data from being deleted
  CONTRIBUTING.md
  cmd/tarmak/cmd/cluster_plan.go
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  packer/amazon/centos-puppet-agent-latest-kernel.json
  packer/amazon/centos-puppet-agent.json
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/packer/image.go
  pkg/packer/packer.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/instance_pool/instance_pool.go
  pkg/tarmak/instance_pool/volume.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/provider/amazon/amazon.go
  pkg/tarmak/provider/amazon/image.go
  pkg/tarmak/terraform.go
  pkg/tarmak/utils/context.go
  pkg/terraform/plan/plan.go
  pkg/terraform/plan/plan_test.go
  pkg/terraform/templating.go
  pkg/terraform/terraform.go
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/instance_pools/instance_pools.tf.template
  terraform/amazon/templates/vault_instances.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#496 Select only images that use the correct encrypted setting
  cmd/tarmak/cmd/cluster_images_list.go
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/packer/packer.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/provider/amazon/amazon.go
  pkg/tarmak/provider/amazon/image.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#537 Bump node-exporter to 0.16.0 and update rules
  puppet/modules/prometheus/README.md
  puppet/modules/prometheus/manifests/node_exporter.pp
  puppet/modules/prometheus/spec/defines/rule_spec.rb
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#554 Make sure node_exporter are restarted correctly
  puppet/modules/prometheus/manifests/node_exporter.pp
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#551 Add an Istio section to examples
  docs/examples/istio.rst
  docs/spelling_wordlist.txt
  docs/user-guide.rst
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#553 Fix node-exporter port on etcd nodes
  puppet/modules/prometheus/manifests/node_exporter.pp
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#539 Add navigator docs section
  docs/examples.rst
  docs/examples/navigator.rst
  docs/spelling_wordlist.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#545 Add docs about using instance storage
  docs/user-guide.rst
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
