Repository jetstack/tarmak, pull requests merged in 2018-10, with the labels that each got.

#561 Adds flags and image to generated API reference documentation
  docs/generated/reference/config.yaml
  docs/generated/reference/output/api-docs.html
  docs/generated/reference/output/navData.js
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#562 Packer image updates
  packer/amazon/centos-puppet-agent-latest-kernel.json
  packer/amazon/centos-puppet-agent.json
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#568 Fix github language detection
  .gitattributes
  puppet/.gitattributes
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#569 Update OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#571 Removes stylesheet.css from /
  stylesheet.css
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#577 Update reference docs node_modules dependencies
  docs/generated/reference/output/node_modules/highlight.js/lib/highlight.js
  docs/generated/reference/output/node_modules/highlight.js/lib/index.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/angelscript.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/arcade.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/cmake.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/cpp.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/cs.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/dart.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/elixir.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/elm.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/gml.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/isbl.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/java.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/kotlin.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/matlab.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/nsis.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/pgsql.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/php.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/plaintext.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/properties.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/protobuf.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/python.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/reasonml.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/sas.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/shell.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/sqf.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/sql.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/swift.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/vbnet.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/vhdl.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/vim.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/xml.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/yaml.js
  docs/generated/reference/output/node_modules/highlight.js/styles/a11y-dark.css
  docs/generated/reference/output/node_modules/highlight.js/styles/a11y-light.css
  docs/generated/reference/output/node_modules/highlight.js/styles/an-old-hope.css
  docs/generated/reference/output/node_modules/highlight.js/styles/atom-one-dark-reasonable.css
  docs/generated/reference/output/node_modules/highlight.js/styles/gml.css
  docs/generated/reference/output/node_modules/highlight.js/styles/isbl-editor-dark.css
  docs/generated/reference/output/node_modules/highlight.js/styles/isbl-editor-light.css
  docs/generated/reference/output/node_modules/highlight.js/styles/lightfair.css
  docs/generated/reference/output/node_modules/highlight.js/styles/nord.css
  docs/generated/reference/output/node_modules/highlight.js/styles/shades-of-purple.css
  docs/generated/reference/output/node_modules/highlight.js/styles/xcode.css
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#570 Improve consul and update
  CHANGELOG.md
  puppet/modules/consul/manifests/config.pp
  puppet/modules/consul/manifests/init.pp
  puppet/modules/consul/manifests/params.pp
  puppet/modules/consul/manifests/service.pp
  puppet/modules/consul/spec/acceptance/single_node_spec.rb
  puppet/modules/consul/spec/acceptance/three_nodes_spec.rb
  puppet/modules/consul/spec/classes/config_spec.rb
  puppet/modules/consul/spec/classes/install_spec.rb
  puppet/modules/consul/spec/classes/service_spec.rb
  puppet/modules/consul/templates/consul.service.erb
  terraform/amazon/modules/vault/templates/vault_user_data.yaml
  terraform/amazon/templates/inputs.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#582 Update and pin highlight.js node_module to 9.13.1
  docs/generated/reference/output/node_modules/highlight.js/lib/highlight.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/angelscript.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/cs.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/reasonml.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/swift.js
  docs/generated/reference/output/node_modules/highlight.js/lib/languages/typescript.js
  hack/brodocs/package.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#580 Ensure static and generated terraform code is formatted according to `terrafrom fmt`
  terraform/amazon/modules/bastion/inputs.tf
  terraform/amazon/modules/bastion/outputs.tf
  terraform/amazon/modules/jenkins/aws.tf
  terraform/amazon/modules/jenkins/inputs.tf
  terraform/amazon/modules/jenkins/jenkins.tf
  terraform/amazon/modules/jenkins/jenkins_iam.tf
  terraform/amazon/modules/jenkins/outputs.tf
  terraform/amazon/modules/kubernetes/inputs.tf
  terraform/amazon/modules/kubernetes/providers.tf
  terraform/amazon/modules/kubernetes/vault.tf
  terraform/amazon/modules/network-existing-vpc/inputs.tf
  terraform/amazon/modules/network/inputs.tf
  terraform/amazon/modules/state/inputs.tf
  terraform/amazon/modules/state/outputs.tf
  terraform/amazon/modules/state/secrets.tf
  terraform/amazon/modules/vault/aws.tf
  terraform/amazon/modules/vault/inputs.tf
  terraform/amazon/modules/vault/outputs.tf
  terraform/amazon/modules/vault/vault_sg.tf
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template
  terraform/amazon/templates/instance_pools/instance_pools.tf.template
  terraform/amazon/templates/instance_pools/role_elb.tf.template
  terraform/amazon/templates/instance_pools/role_security_group.tf.template
  terraform/amazon/templates/instance_pools/role_variables.tf.template
  terraform/amazon/templates/jenkins_elb.tf.template
  terraform/amazon/templates/modules.tf.template
  terraform/amazon/templates/outputs.tf.template
  terraform/amazon/templates/providers.tf.template
  terraform/amazon/templates/vault_instances.tf.template
  terraform/amazon/templates/wing_s3.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#419 Removes unused stack related parameters
  cmd/tarmak/cmd/cluster.go
  cmd/tarmak/cmd/cluster_apply.go
  docs/design_cli_ux.rst
  docs/generated/reference/output/api-docs.html
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/apis/tarmak/v1alpha1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#576 Improve error when remote state is destroyed
  pkg/tarmak/terraform.go
  pkg/terraform/templating.go
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#535 Test generated terraform code
  cmd/tarmak/cmd/cluster_apply.go
  cmd/tarmak/cmd/cluster_debug_terraform_shell.go
  cmd/tarmak/cmd/cluster_destroy.go
  cmd/tarmak/cmd/cluster_images_build.go
  cmd/tarmak/cmd/cluster_images_list.go
  cmd/tarmak/cmd/cluster_init.go
  cmd/tarmak/cmd/cluster_kubectl.go
  cmd/tarmak/cmd/cluster_plan.go
  cmd/tarmak/cmd/cluster_set-current.go
  cmd/tarmak/cmd/environment_init.go
  cmd/tarmak/cmd/provider_init.go
  cmd/tarmak/cmd/provider_validate.go
  cmd/tarmak/cmd/terraform.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/tarmak_test.go
  pkg/tarmak/terraform.go
  pkg/tarmak/utils/context.go
  pkg/terraform/passthrough.go
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#558 Adds etcd snapshot backups to S3
  puppet/hieradata/role/etcd.yaml
  puppet/modules/consul/manifests/service.pp
  puppet/modules/consul/templates/consul-backup.service.erb
  puppet/modules/etcd/files/minio-server.service
  puppet/modules/etcd/files/minio-server.sh
  puppet/modules/etcd/manifests/backup.pp
  puppet/modules/etcd/manifests/init.pp
  puppet/modules/etcd/manifests/install.pp
  puppet/modules/etcd/manifests/instance.pp
  puppet/modules/etcd/manifests/params.pp
  puppet/modules/etcd/spec/acceptance/single_node_spec.rb
  puppet/modules/etcd/spec/defines/backup_spec.rb
  puppet/modules/etcd/templates/etcd-backup.service.erb
  puppet/modules/etcd/templates/etcd-backup.sh.erb
  puppet/modules/etcd/templates/etcd-backup.timer.erb
  puppet/modules/tarmak/manifests/etcd.pp
  puppet/spec/hosts/etcd_spec.rb
  terraform/amazon/modules/kubernetes/inputs.tf
  terraform/amazon/modules/kubernetes/templates/iam_etcd_backup_bucket_write.json
  terraform/amazon/modules/vault/outputs.tf
  terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/modules.tf.template
  terraform/amazon/templates/outputs.tf.template
  terraform/amazon/templates/puppet_agent_user_data.yaml.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#587 Move tarmak sock to /tmp and ensure cleanup
  cmd/tarmak/cmd/cluster_force-unlock.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/utils/context.go
  pkg/terraform/templating.go
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#594 Re-add elb_access_logs_internal_bucket_interval
  terraform/amazon/templates/modules.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#596 Fix broken cluster API link
  docs/introduction.rst
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#579 Enables additional policies for bastion and vault instance pools
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/tarmak/cluster/cluster.go
  terraform/amazon/modules/bastion/bastion.tf
  terraform/amazon/modules/bastion/bastion_iam.tf
  terraform/amazon/modules/bastion/inputs.tf
  terraform/amazon/modules/bastion/templates/role.json
  terraform/amazon/modules/vault/inputs.tf
  terraform/amazon/modules/vault/vault_iam.tf
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#602 Remove myself from OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#610 Automated cherry pick of #532 #596 origin release 0.4
  docs/Makefile
  docs/introduction.rst
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#609 Automated cherry pick of #512 #536 origin release 0.4
  pkg/tarmak/environment/bastion.go
  pkg/tarmak/vault/vault.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#605 Adds restart on failure to consul service
  terraform/amazon/modules/vault/templates/vault_user_data.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#604 Better image build control
  cmd/tarmak/cmd/cluster.go
  cmd/tarmak/cmd/cluster_apply.go
  cmd/tarmak/cmd/cluster_debug_terraform_shell.go
  cmd/tarmak/cmd/cluster_destroy.go
  cmd/tarmak/cmd/cluster_force-unlock.go
  cmd/tarmak/cmd/cluster_images_build.go
  cmd/tarmak/cmd/cluster_plan.go
  docs/generated/cmd/tarmak/tarmak_clusters_images.rst
  docs/generated/cmd/tarmak/tarmak_clusters_images_build.rst
  docs/generated/reference/output/api-docs.html
  docs/generated/reference/output/navData.js
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/apis/tarmak/v1alpha1/zz_generated.deepcopy.go
  pkg/packer/image.go
  pkg/packer/packer.go
  pkg/tarmak/cmd.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/utils/slices.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
