Repository jetstack/tarmak, pull requests merged in 2018-05, with the labels that each got.

#202 Fix typo
  pkg/apis/cluster/v1alpha1/cluster.go
Labels: approved, lgtm, release-note-none, size/XS

#206 Show zone info from config when doing `cluster list`
  cmd/tarmak/cmd/cluster_list.go
Labels: approved, lgtm, release-note-none, size/XS

#211 Toggle SELinux volume label based on OS version
  .gitignore
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
Labels: approved, lgtm, release-note, size/S

#205 Install the aws-cli from pip
  packer/amazon/centos-puppet-agent-latest-kernel.json
  packer/amazon/centos-puppet-agent.json
  puppet/modules/aws_ebs/manifests/init.pp
  terraform/amazon/modules/vault/templates/vault_user_data.yaml
Labels: approved, lgtm, release-note, size/M

#208 Fix default file path expansion
  pkg/tarmak/tarmak.go
Labels: approved, lgtm, release-note, size/XS

#144 Update Prometheus
  puppet/modules/prometheus/Makefile
  puppet/modules/prometheus/README.md
  puppet/modules/prometheus/documentation.json
  puppet/modules/prometheus/manifests/blackbox_exporter.pp
  puppet/modules/prometheus/manifests/server.pp
  puppet/modules/prometheus/templates/kube-state-metrics-deployment.yaml.erb
Labels: approved, lgtm, release-note, size/S

#201 Update calico manifests to v3.1.1
  puppet/modules/calico/manifests/node.pp
  puppet/modules/calico/manifests/policy_controller.pp
  puppet/modules/calico/spec/classes/config_spec.rb
  puppet/modules/calico/templates/configmap.yaml.erb
  puppet/modules/calico/templates/node-daemonset.yaml.erb
  puppet/modules/calico/templates/node-rbac.yaml.erb
  puppet/modules/calico/templates/policy-controller-deployment.yaml.erb
Labels: approved, lgtm, release-note, size/L

#212 Add some snippet to troubleshoot calicoctl
  docs/index.rst
  docs/spelling_wordlist.txt
  docs/troubleshooting.rst
  docs/troubleshooting/calico.rst
Labels: approved, lgtm, release-note-none, size/M

#214 Update calcio version CHANGELOG.md
  CHANGELOG.md
Labels: approved, lgtm, release-note-none

#213 Kube-proxy ipvsadm and conntrack
  puppet/modules/kubernetes/manifests/proxy.pp
Labels: approved, lgtm, release-note-none, size/S

#142 Locks down master and worker role policies
  pkg/tarmak/cluster/roles.go
  pkg/tarmak/role/role.go
  terraform/amazon/modules/kubernetes/iam_policies.tf
  terraform/amazon/modules/kubernetes/templates/etcd_role_policy.json
  terraform/amazon/modules/kubernetes/templates/iam_cluster_autoscaler.json
  terraform/amazon/modules/kubernetes/templates/iam_ec2_controller.json
  terraform/amazon/modules/kubernetes/templates/iam_ec2_full.json
  terraform/amazon/modules/kubernetes/templates/iam_ec2_read.json
  terraform/amazon/modules/kubernetes/templates/iam_elb_controller.json
  terraform/amazon/modules/kubernetes/templates/iam_elb_full.json
  terraform/amazon/modules/kubernetes/templates/kubernetes_master_role_policy.json
  terraform/amazon/modules/kubernetes/templates/kubernetes_worker_role_policy.json
  terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template
Labels: approved, area/security, lgtm, priority/P0, release-note, size/L

#215 Enable iptables processing for bridges
  puppet/modules/kubernetes/templates/kube-proxy.service.erb
Labels: approved, lgtm, release-note, size/XS

#216 Respect network CIDRs configured in tarmak.yaml
  pkg/puppet/puppet.go
  puppet/modules/calico/manifests/init.pp
  puppet/modules/calico/manifests/node.pp
  puppet/modules/kubernetes/manifests/controller_manager.pp
  puppet/modules/kubernetes/manifests/init.pp
  puppet/modules/kubernetes/templates/kube-controller-manager.service.erb
  puppet/modules/kubernetes/templates/kube-proxy.service.erb
  puppet/modules/tarmak/manifests/init.pp
  puppet/modules/tarmak/manifests/overlay_calico.pp
Labels: approved, lgtm, release-note-none, size/S

#220 Reenable tagging of subnets
  terraform/amazon/modules/kubernetes/tags.tf
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, release-note-none, size/S

#221 Fix kernel network device names
  packer/amazon/centos-puppet-agent-latest-kernel.json
Labels: approved, lgtm, release-note-none, size/XS

#219 Fix calico's IPIP protocol rule
  pkg/tarmak/cluster/firewall/rules.go
Labels: approved, lgtm, release-note-none, size/XS

#217 Update kubernetes versions
  CHANGELOG.md
  pkg/apis/cluster/v1alpha1/defaults.go
  puppet/modules/kubernetes/manifests/params.pp
  puppet/modules/tarmak/Makefile
  puppet/modules/tarmak/manifests/params.pp
  puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
Labels: approved, lgtm, release-note, size/S

#218 Use centos with rhel kernel as default image
  pkg/apis/cluster/v1alpha1/defaults.go
Labels: approved, lgtm, release-note-none, size/XS

#231 Relax tarmak puppet module dependency versions
  puppet/modules/tarmak/metadata.json
Labels: approved, lgtm, release-note, size/S

#229 Ignore .kube directories
  .gitignore
Labels: approved, lgtm, release-note, size/XS

#228 Fetch latest selinux package for kubelet config
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
Labels: approved, lgtm, release-note, size/L

#233 Restart the wing agent service on-failure
  terraform/amazon/modules/kubernetes/templates/puppet_agent_user_data.yaml
Labels: approved, lgtm, release-note, size/XS

#225 Add PodSecurityPolicies
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/puppet/puppet.go
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/manifests/init.pp
  puppet/modules/kubernetes/manifests/master.pp
  puppet/modules/kubernetes/manifests/pod_security_policy.pp
  puppet/modules/kubernetes/spec/acceptance/single_node_spec.rb
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
  puppet/modules/kubernetes/templates/pod-security-policy-rbac.yaml.erb
  puppet/modules/kubernetes/templates/pod-security-policy.yaml.erb
  puppet/modules/tarmak/manifests/init.pp
  puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
Labels: approved, lgtm, release-note, size/L

#237 Include unstaged files in docker_build
  Makefile
  cmd/tarmak/cmd/cluster_plan.go
Labels: approved, lgtm, release-note-none, size/XS

#236 Config option to add additional IAM policies
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/instancepool.go
  pkg/tarmak/instance_pool/instance_pool.go
  terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template
Labels: approved, lgtm, release-note, size/M

#232 Configure apiserver auditing
  puppet/modules/kubernetes/files/audit-policy.yaml
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Labels: approved, lgtm, release-note, size/L

#207 Add Puppet development docs
  docs/developer-guide.rst
Labels: approved, lgtm, release-note-none, size/M

#197 Implement log forwarding with fluent-bit
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/cluster/v1alpha1/logging.go
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/puppet/puppet.go
  pkg/tarmak/cluster/cluster.go
  puppet/modules/.gitignore
  puppet/modules/aws_es_proxy/.fixtures.yml
  puppet/modules/aws_es_proxy/Gemfile
  puppet/modules/aws_es_proxy/Gemfile.lock
  puppet/modules/aws_es_proxy/Makefile
  puppet/modules/aws_es_proxy/README.md
  puppet/modules/aws_es_proxy/Rakefile
  puppet/modules/aws_es_proxy/manifests/init.pp
  puppet/modules/aws_es_proxy/manifests/install.pp
  puppet/modules/aws_es_proxy/manifests/instance.pp
  puppet/modules/aws_es_proxy/manifests/params.pp
  puppet/modules/aws_es_proxy/metadata.json
  puppet/modules/aws_es_proxy/spec/acceptance/fluentbit_spec.rb
  puppet/modules/aws_es_proxy/spec/acceptance/nodesets/default.yml
  puppet/modules/aws_es_proxy/spec/classes/init_spec.rb
  puppet/modules/aws_es_proxy/spec/defines/instance_spec.rb
  puppet/modules/aws_es_proxy/spec/spec_helper.rb
  puppet/modules/aws_es_proxy/spec/spec_helper_acceptance.rb
  puppet/modules/aws_es_proxy/templates/aws-es-proxy.service.erb
  puppet/modules/fluent_bit/.fixtures.yml
  puppet/modules/fluent_bit/.gitignore
  puppet/modules/fluent_bit/.gitlab-ci.yml
  puppet/modules/fluent_bit/.travis.yml
  puppet/modules/fluent_bit/Gemfile
  puppet/modules/fluent_bit/Gemfile.lock
  puppet/modules/fluent_bit/Makefile
  puppet/modules/fluent_bit/README.md
  puppet/modules/fluent_bit/Rakefile
  puppet/modules/fluent_bit/files/td-agent-bit.repo
  puppet/modules/fluent_bit/manifests/config.pp
  puppet/modules/fluent_bit/manifests/daemonset.pp
  puppet/modules/fluent_bit/manifests/init.pp
  puppet/modules/fluent_bit/manifests/install.pp
  puppet/modules/fluent_bit/manifests/output.pp
  puppet/modules/fluent_bit/manifests/params.pp
  puppet/modules/fluent_bit/manifests/service.pp
  puppet/modules/fluent_bit/metadata.json
  puppet/modules/fluent_bit/spec/acceptance/fluentbit_spec.rb
  puppet/modules/fluent_bit/spec/acceptance/nodesets/default.yml
  puppet/modules/fluent_bit/spec/classes/daemonset_spec.rb
  puppet/modules/fluent_bit/spec/classes/init_spec.rb
  puppet/modules/fluent_bit/spec/defines/output_spec.rb
  puppet/modules/fluent_bit/spec/spec_helper.rb
  puppet/modules/fluent_bit/spec/spec_helper_acceptance.rb
  puppet/modules/fluent_bit/templates/fluent-bit-configmap.yaml.erb
  puppet/modules/fluent_bit/templates/fluent-bit-daemonset.yaml.erb
  puppet/modules/fluent_bit/templates/td-agent-bit-output.conf.erb
  puppet/modules/fluent_bit/templates/td-agent-bit.conf.erb
  puppet/modules/tarmak/manifests/fluent_bit.pp
  puppet/modules/tarmak/manifests/init.pp
  puppet/modules/tarmak/manifests/params.pp
Labels: approved, lgtm, release-note, size/XXL

#241 Add an AWS Elasticsearch example
  docs/user-guide.rst
  docs/user-guide/aws-elasticsearch/elasticsearch.tf
Labels: approved, lgtm, release-note-none, size/L

#242 Add local build option to makefile
  .gitignore
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#247 Write ssh config at tarmak initialisation to ensure present
  pkg/tarmak/tarmak.go
  pkg/tarmak/terraform.go
Labels: approved, lgtm, release-note, size/S

#226 Re-implements interactive shell for terraform debug shell
  cmd/tarmak/cmd/cluster_debug_terraform_shell.go
  cmd/tarmak/cmd/terraform.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, release-note, size/M

#249 Ensure templated files are truncated
  pkg/terraform/templating.go
Labels: approved, lgtm, release-note, size/S

#210 Fix cluster list filter
  cmd/tarmak/cmd/cluster_list.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/environment/bastion.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/provider/amazon/hosts.go
  pkg/tarmak/ssh.go
  pkg/tarmak/ssh/ssh.go
Labels: approved, lgtm, release-note-none, size/L

#240 Add Jenkins module to Terraform stack
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/cluster/roles.go
  pkg/terraform/templating.go
  terraform/amazon/modules/jenkins/aws.tf
  terraform/amazon/modules/jenkins/inputs.tf
  terraform/amazon/modules/jenkins/jenkins.tf
  terraform/amazon/modules/jenkins/jenkins_iam.tf
  terraform/amazon/modules/jenkins/outputs.tf
  terraform/amazon/modules/jenkins/templates/jenkins_role_policy.json
  terraform/amazon/modules/jenkins/templates/jenkins_user_data.yaml
  terraform/amazon/modules/jenkins/templates/role.json
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/instance_pools/instance_pools.tf.template
  terraform/amazon/templates/instance_pools/role_elb.tf.template
  terraform/amazon/templates/instance_pools/role_variables.tf.template
  terraform/amazon/templates/jenkins_elb.tf.template
  terraform/amazon/templates/modules.tf.template
  terraform/amazon/templates/outputs.tf.template
Labels: approved, lgtm, release-note, size/XL

#250 Update ssh config write to use latest interface
  pkg/tarmak/tarmak.go
Labels: approved, lgtm, release-note, size/XS

#253 Suppress provider log output
  pkg/terraform/passthrough.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, release-note-none, size/XS

#251 Add Jenkins docs
  docs/spelling_wordlist.txt
  docs/user-guide.rst
Labels: approved, lgtm, release-note-none, size/M

#185 Fix kubectl
  cmd/tarmak/cmd/kubectl.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/kubectl/kubectl.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, release-note, size/M

#254 Catch exit code 2 from terraform plan
  cmd/tarmak/cmd/cluster_plan.go
  pkg/tarmak/utils/context.go
Labels: approved, lgtm, release-note-none, size/S

#262 Adds backoff to wing client set
  pkg/tarmak/cluster/wing.go
  pkg/tarmak/environment/bastion.go
  pkg/wing/puppet.go
Labels: approved, lgtm, release-note-none, size/M

#260 OIDC documentation
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Labels: approved, lgtm, release-note, size/M

#248 Throw error when we can't find the image ID (AMI) for an instance pool
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/terraform.go
Labels: approved, lgtm, release-note, size/M

#266 Ensure environment is passed through for kubectl
  pkg/tarmak/kubectl/kubectl.go
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#265 Upgrade default tiller version to 2.9.1
  puppet/modules/kubernetes_addons/manifests/tiller.pp
  puppet/modules/kubernetes_addons/spec/classes/tiller_spec.rb
  puppet/modules/kubernetes_addons/templates/tiller-deployment.yaml.erb
Labels: approved, lgtm, release-note, size/M

#256 Implement wing development mode
  .gitignore
  Makefile
  cmd/tarmak/cmd/init.go
  cmd/tarmak/cmd/root.go
  cmd/tarmak/cmd/version.go
  cmd/tarmak/main.go
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/tarmak/assets/assets.go
  pkg/tarmak/assets/assets_dev.go
  pkg/tarmak/config/config.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/tarmak_test.go
  pkg/terraform/templating.go
  pkg/terraform/terraform.go
  terraform/amazon/modules/kubernetes/iam_policies.tf
  terraform/amazon/modules/kubernetes/templates/iam_tarmak_bucket_read.json
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/puppet_agent_user_data.yaml.template
  terraform/amazon/templates/wing_s3.tf.template
Labels: approved, lgtm, release-note, size/L

#263 Implement an external scrape mode for prometheus
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/puppet/puppet.go
  pkg/puppet/puppet_test.go
  puppet/hieradata/common.yaml
  puppet/hieradata/role/etcd.yaml
  puppet/hieradata/role/master.yaml
  puppet/hieradata/role/worker.yaml
  puppet/modules/prometheus/manifests/init.pp
  puppet/modules/prometheus/manifests/node_exporter.pp
  puppet/modules/prometheus/manifests/server.pp
  puppet/modules/prometheus/templates/prometheus-config-global.yaml.erb
Labels: approved, lgtm, release-note, size/XL

#268 Tiller prom docs
  docs/spelling_wordlist.txt
  docs/user-guide.rst
Labels: approved, kind/documentation, lgtm, release-note-none, size/L

#272 Update vault-helper to fix certificate renewal
  Gopkg.lock
  Gopkg.toml
  puppet/modules/vault_client/manifests/params.pp
Labels: approved, lgtm, release-note, size/S

#270 Add subnets/availability zones to the hub instance pools
  pkg/tarmak/cluster/init.go
Labels: approved, lgtm, release-note, size/XS

#271 Change resource so that we can run a clean terraform destroy
  terraform/amazon/modules/bastion/bastion.tf
  terraform/amazon/modules/bastion/outputs.tf
  terraform/amazon/modules/jenkins/outputs.tf
  terraform/amazon/modules/network/igw.tf
  terraform/amazon/modules/network/outputs.tf
  terraform/amazon/modules/network/route53.tf
  terraform/amazon/modules/network/routes.tf
  terraform/amazon/modules/network/subnets.tf
  terraform/amazon/modules/network/vpc.tf
  terraform/amazon/modules/network/vpc_endpoints.tf
  terraform/amazon/modules/network/vpc_peering.tf
  terraform/amazon/modules/vault/outputs.tf
  terraform/amazon/modules/vault/tls.tf
  terraform/amazon/modules/vault/tls_s3.tf
  terraform/amazon/modules/vault/vault_dns.tf
  terraform/amazon/modules/vault/vault_instances.tf
  terraform/amazon/modules/vault/vault_sg.tf
  terraform/amazon/templates/instance_pools/role_elb.tf.template
Labels: approved, lgtm, release-note, size/M
