Repository jetstack/tarmak, pull requests merged in 2018-11, with the labels that each got.

#611 Fix escaping issue for kubectl and ssh arguments
  cmd/tarmak/cmd/root.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#585 Bump fluent bit daemonset to latest version
  hack/fluentbit-repo/Dockerfile
  hack/fluentbit-repo/Makefile
  hack/fluentbit-repo/README.md
  puppet/modules/fluent_bit/files/td-agent-bit.repo
  puppet/modules/fluent_bit/manifests/daemonset.pp
  puppet/modules/fluent_bit/manifests/install.pp
  puppet/modules/fluent_bit/manifests/params.pp
  puppet/modules/fluent_bit/templates/td-agent-bit.repo.erb
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#614 Adds KMS SSE to consul backups
  terraform/amazon/modules/vault/templates/vault_user_data.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#560 Adds auto-approve and auto-approve-deleting-data flags to cluster apply
  cmd/tarmak/cmd/cluster.go
  docs/generated/cmd/tarmak/tarmak_clusters_apply.rst
  docs/generated/reference/output/api-docs.html
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/tarmak/cmd.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/tarmak.go
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#504 Encrypt puppet tar ball
  cmd/tarmak/cmd/terraform.go
  pkg/tarmak/cluster/configuration.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/provider/amazon/kv.go
  pkg/tarmak/provider/amazon/tf_remote_state.go
  pkg/tarmak/provider/amazon/upload_config.go
  pkg/terraform/passthrough.go
  pkg/terraform/plan/plan.go
  pkg/terraform/plan/plan_test.go
  pkg/terraform/terraform.go
  pkg/wing/provider/file/file.go
  pkg/wing/provider/hash/hash.go
  pkg/wing/provider/provider.go
  pkg/wing/provider/s3/s3.go
  pkg/wing/puppet.go
  pkg/wing/wing.go
  puppet/modules/consul/files/consul-backup.sh
  terraform/amazon/modules/kubernetes/iam_policies.tf
  terraform/amazon/modules/kubernetes/puppet_s3.tf
  terraform/amazon/modules/kubernetes/templates/iam_tarmak_bucket_read.json
  terraform/amazon/modules/kubernetes/vault.tf
  terraform/amazon/modules/state/secrets.tf
  terraform/amazon/modules/vault/templates/vault_user_data.yaml
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/puppet_agent_user_data.yaml.template
  terraform/amazon/templates/vault_instances.tf.template
Labels: approved, dco-signoff: yes, lgtm, priority/P1, release-note, size/L

#573 Ensure ssh key file holds correct permissions and can be parsed
  pkg/tarmak/environment/environment.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/ssh.go
  pkg/tarmak/ssh/ssh.go
  pkg/tarmak/tarmak.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#598 Exit sooner when wrong force-unlock len(args)
  cmd/tarmak/cmd/cluster_force-unlock.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#597 Clean up ssh run time assets
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/provider/amazon/hosts.go
  pkg/tarmak/ssh/ssh.go
  pkg/tarmak/tarmak.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#622 Upgrade Calico to 3.1.4
  CHANGELOG.md
  puppet/modules/calico/manifests/node.pp
  puppet/modules/calico/manifests/policy_controller.pp
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#623 Upgrade etcd to 3.2.25
  CHANGELOG.md
  puppet/modules/etcd/manifests/params.pp
  puppet/modules/etcd/spec/acceptance/single_node_spec.rb
  puppet/modules/etcd/spec/acceptance/three_node_spec.rb
  puppet/modules/kubernetes/files/etcd.service
  puppet/modules/tarmak/README.md
  puppet/modules/tarmak/manifests/init.pp
  terraform/amazon/modules/bastion/templates/bastion_user_data.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#624 Upgrade Prometheus
  puppet/modules/kubernetes_addons/manifests/metrics_server.pp
  puppet/modules/kubernetes_addons/manifests/params.pp
  puppet/modules/prometheus/Makefile
  puppet/modules/prometheus/README.md
  puppet/modules/prometheus/manifests/kube_state_metrics.pp
  puppet/modules/prometheus/manifests/server.pp
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#440 Unset deprecated flags from 1.11
  docs/generated/reference/output/api-docs.html
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/puppet/puppet.go
  pkg/tarmak/cluster/cluster.go
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/manifests/init.pp
  puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#626 Adds backoff to describe reserved instance offerings
  pkg/tarmak/provider/amazon/amazon.go
  pkg/tarmak/utils/consts/consts.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#603 Fix For Jenkins instances
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/instance_pool/instance_pool.go
  pkg/tarmak/interfaces/interfaces.go
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/instance_pools/instance_pools.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#630 Run plan again if puppet tar gz has been tainted
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#631 Use consistent log output
  pkg/tarmak/utils/context.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#625 Adds Jenkins instance pool tests to tarmak_test.go
  pkg/tarmak/config/cluster.go
  pkg/tarmak/tarmak_test.go
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/instance_pools/instance_pools.tf.template
  terraform/amazon/templates/instance_pools/role_elb.tf.template
  terraform/amazon/templates/modules.tf.template
  terraform/amazon/templates/outputs.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#633 Update Gopkg.lock
  Gopkg.lock
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#629 Stop hub destroy returning error
  terraform/amazon/modules/network/outputs.tf
  terraform/amazon/modules/state/outputs.tf
  terraform/amazon/modules/vault/inputs.tf
  terraform/amazon/modules/vault/outputs.tf
  terraform/amazon/modules/vault/vault_iam.tf
  terraform/amazon/templates/vault_instances.tf.template
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#566 Use hub in after inits of multi cluster environments
  pkg/tarmak/tarmak.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#559 Fix bug when running tarmak init with empty .tarmak directory
  pkg/tarmak/provider/amazon/amazon.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#493 Only converge on wing when not in infrastructure only
  cmd/tarmak/cmd/cluster.go
  docs/generated/cmd/tarmak/tarmak_clusters_apply.rst
  docs/generated/reference/output/api-docs.html
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/tarmak/cmd.go
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#442 Kublet and Kube-Proxy config file
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/manifests/proxy.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/spec/classes/proxy_spec.rb
  puppet/modules/kubernetes/templates/kube-proxy-config.yaml.erb
  puppet/modules/kubernetes/templates/kube-proxy.service.erb
  puppet/modules/kubernetes/templates/kubelet-config.yaml.erb
  puppet/modules/kubernetes/templates/kubelet.service.erb
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#637 Do not auto-approve state deletes by default
  cmd/tarmak/cmd/cluster.go
  docs/generated/cmd/tarmak/tarmak_clusters_apply.rst
  pkg/terraform/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#639 Kube bench proposed security fixes
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/manifests/init.pp
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
  puppet/modules/kubernetes/templates/kube-controller-manager.service.erb
  puppet/modules/kubernetes/templates/kube-scheduler.service.erb
  puppet/modules/kubernetes/templates/kubelet-config.yaml.erb
  puppet/modules/kubernetes/templates/kubelet.service.erb
Labels: approved, area/security, dco-signoff: yes, lgtm, release-note, size/M

#641 Fix panic when initing environment and validating ssh
  pkg/tarmak/ssh/ssh.go
  pkg/tarmak/tarmak.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#572 Use vault-helper dry run ensure
  pkg/terraform/providers/tarmak/resource_vault_cluster.go
  pkg/terraform/providers/tarmak/resource_vault_instance_role.go
  pkg/terraform/providers/tarmak/rpc/bastion_instance_status.go
  pkg/terraform/providers/tarmak/rpc/rpc.go
  pkg/terraform/providers/tarmak/rpc/vault_cluster_status.go
  pkg/terraform/providers/tarmak/rpc/vault_instance_role.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#621 Disable cobra flags after kubectl sub-command
  cmd/tarmak/cmd/cluster_instances_ssh.go
  cmd/tarmak/cmd/cluster_kubectl.go
  cmd/tarmak/cmd/cluster_ssh.go
  cmd/tarmak/cmd/root.go
  cmd/tarmak/cmd/tarmak_test.go
  docs/generated/cmd/tarmak/tarmak_clusters_instances_ssh.rst
  docs/generated/cmd/tarmak/tarmak_clusters_ssh.rst
  docs/generated/cmd/tarmak/tarmak_kubectl.rst
  pkg/tarmak/utils/slices.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#619 Adds ability to change vault-helper url in tarmak.yaml
  docs/generated/reference/output/api-docs.html
  docs/generated/reference/output/navData.js
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/puppet/puppet.go
  puppet/modules/vault_client/manifests/init.pp
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
