Repository jetstack/tarmak, pull requests merged in 2018-03, with the labels that each got.

#74 vault helper docs
  docs/index.rst
  docs/spelling_wordlist.txt
  docs/vault-helper-guide.rst
  docs/vault-setup-config.rst
Labels: approved, lgtm, release-note-none, size/M

#123 Clean up SSH tunnels properly
  pkg/tarmak/ssh/tunnel.go
Labels: approved, lgtm, release-note, size/M

#125 Use same local IP as tunnel binds to
  pkg/tarmak/kubectl/kubectl.go
Labels: approved, lgtm, release-note, size/XS

#127 Clean up tarmak after execution
  cmd/tarmak/cmd/cluster_apply.go
  cmd/tarmak/cmd/cluster_debug_puppet_build-tar.go
  cmd/tarmak/cmd/cluster_debug_terraform_shell.go
  cmd/tarmak/cmd/cluster_destroy.go
  cmd/tarmak/cmd/cluster_images_build.go
  cmd/tarmak/cmd/cluster_images_list.go
  cmd/tarmak/cmd/cluster_init.go
  cmd/tarmak/cmd/cluster_instances_list.go
  cmd/tarmak/cmd/cluster_instances_ssh.go
  cmd/tarmak/cmd/cluster_kubectl.go
  cmd/tarmak/cmd/cluster_list.go
  cmd/tarmak/cmd/cluster_ssh.go
  cmd/tarmak/cmd/environment_init.go
  cmd/tarmak/cmd/environment_list.go
  cmd/tarmak/cmd/kubectl.go
  cmd/tarmak/cmd/provider_init.go
  cmd/tarmak/cmd/provider_list.go
  cmd/tarmak/cmd/provider_validate.go
  pkg/tarmak/tarmak.go
Labels: approved, lgtm, release-note-none, size/S

#130 Fix tarmak kubectl tunnel
  pkg/tarmak/kubectl/kubectl.go
  pkg/tarmak/ssh/tunnel.go
Labels: approved, lgtm, release-note-none, size/M

#134 Read tarmak's config folder from the environment
  cmd/tarmak/cmd/root.go
Labels: approved, lgtm, release-note-none, size/XS

#136 Configure docker to use the json log format
  puppet/modules/site_module/templates/docker.erb
Labels: approved, lgtm, release-note, size/XS

#135 Fix argument parsing for pass through commands
  cmd/tarmak/cmd/cluster_kubectl.go
  cmd/tarmak/cmd/kubectl.go
  cmd/tarmak/cmd/root.go
  cmd/tarmak/main.go
Labels: approved, lgtm, release-note, size/M

#121 Validate kubelet certificates when called by the apiserver
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  puppet/modules/kubernetes/labels.yaml
  puppet/modules/kubernetes/manifests/params.pp
  puppet/modules/kubernetes/spec/acceptance/single_node_spec.rb
  puppet/modules/kubernetes/spec/classes/controller_manager_spec.rb
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
  puppet/modules/kubernetes/templates/kubelet.service.erb
  puppet/modules/tarmak/Makefile
  puppet/modules/tarmak/manifests/worker.pp
  puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
  puppet/modules/vault_client/Gemfile.lock
  puppet/modules/vault_client/files/vault-add-hostname.sh
  puppet/modules/vault_client/files/vault-dev-server.service
  puppet/modules/vault_client/manifests/params.pp
  puppet/modules/vault_client/spec/acceptance/standard_spec.rb
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_pki_roles.go
Labels: approved, area/security, lgtm, release-note, size/M

#143 Updates etcd to 3.2.17
  CHANGELOG.md
  puppet/modules/etcd/Makefile
  puppet/modules/etcd/labels.yaml
  puppet/modules/etcd/manifests/params.pp
  puppet/modules/etcd/spec/acceptance/nodesets/3n-cluster.yml
  puppet/modules/etcd/spec/acceptance/nodesets/default.yml
  puppet/modules/etcd/spec/acceptance/single_node_spec.rb
  puppet/modules/etcd/spec/acceptance/three_node_spec.rb
  puppet/modules/kubernetes/files/etcd.service
  puppet/modules/tarmak/README.md
  puppet/modules/tarmak/manifests/init.pp
  terraform/amazon/tools/templates/bastion_user_data.yaml
Labels: approved, lgtm, release-note-none, size/L

#146 Add task to build docs using docker
  docs/.dockerignore
  docs/Dockerfile
  docs/Makefile
  docs/developer-guide.rst
Labels: approved, lgtm, release-note, size/M

#147 Adjust introduction wording
  docs/design_cli_ux.rst
  docs/introduction.rst
  docs/spelling_wordlist.txt
Labels: approved, lgtm, release-note-none, size/L

#151 Add page about centos aws license
  docs/aws-centos-guide.rst
  docs/images/aws_centos/step1.png
  docs/images/aws_centos/step2.png
  docs/images/aws_centos/step3.png
  docs/index.rst
  docs/user-guide.rst
Labels: approved, lgtm, release-note, size/M

#152 Update build instructions
  docs/developer-guide.rst
Labels: approved, lgtm, release-note-none, size/XS

#153 Kube-apiserver should use endpoint reconciler in 1.9+
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Labels: approved, lgtm, release-note, size/XS

#137 Put container runtime resources into a separate slice
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
  puppet/modules/kubernetes/templates/kube-controller-manager.service.erb
  puppet/modules/kubernetes/templates/kube-proxy.service.erb
  puppet/modules/kubernetes/templates/kube-scheduler.service.erb
  puppet/modules/kubernetes/templates/kubelet.service.erb
  puppet/modules/site_module/manifests/docker_config.pp
Labels: approved, lgtm, release-note, size/L
