Repository jetstack/tarmak, pull requests merged in 2018-07, with the labels that each got.

#352 Prometheus Install Modes
  Gopkg.lock
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/puppet/puppet.go
  pkg/tarmak/cluster/cluster.go
  puppet/modules/prometheus/manifests/blackbox_exporter.pp
  puppet/modules/prometheus/manifests/blackbox_exporter_etcd.pp
  puppet/modules/prometheus/manifests/init.pp
  puppet/modules/prometheus/manifests/node_exporter.pp
  puppet/modules/prometheus/manifests/params.pp
  puppet/modules/prometheus/manifests/server.pp
  puppet/modules/prometheus/spec/classes/blackbox_exporter_etcd_spec.rb
  puppet/modules/prometheus/spec/classes/node_exporter_spec.rb
  puppet/modules/prometheus/spec/classes/rules_spec.rb
  puppet/modules/prometheus/spec/defines/scrape_config_spec.rb
  puppet/modules/prometheus/templates/prometheus-config.yaml.erb
  puppet/modules/tarmak/manifests/init.pp
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
Labels: approved, lgtm, release-note, size/XXL

#307 Adds set-current cluster subcommand
  cmd/tarmak/cmd/cluster_set-current.go
Labels: approved, lgtm, release-note, size/M

#347 Validate cluster instance pools
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/cluster/cluster_test.go
  pkg/tarmak/interfaces/interfaces.go
Labels: approved, lgtm, release-note-none, size/L

#295 Kube2iam docs
  docs/examples.rst
  docs/examples/kube2iam.rst
  docs/index.rst
  docs/spelling_wordlist.txt
Labels: approved, lgtm, release-note-none, size/L

#344 Improve multi cluster hub error
  docs/user-guide.rst
  pkg/tarmak/cluster/cluster.go
Labels: approved, lgtm, release-note, size/M

#235 vault-helper dry run and delete
  pkg/tarmak/environment/environment.go
  pkg/tarmak/provider/amazon/amazon.go
  pkg/tarmak/vault/vault.go
  pkg/terraform/providers/tarmak/resource_vault_cluster.go
  pkg/terraform/providers/tarmak/resource_vault_instance_role.go
  pkg/terraform/providers/tarmak/rpc/rpc.go
  pkg/terraform/providers/tarmak/rpc/vault_cluster_status.go
  pkg/terraform/providers/tarmak/rpc/vault_instance_role.go
  terraform/amazon/modules/kubernetes/inputs.tf
  terraform/amazon/modules/kubernetes/vault.tf
  terraform/amazon/modules/vault/inputs.tf
  terraform/amazon/modules/vault/vault_instances.tf
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, release-note, size/L

#365 Scrape controller-managers and schedulers
  puppet/modules/prometheus/manifests/server.pp
Labels: approved, lgtm, release-note, size/M

#345 Upgrade Tiller puppet module and docs
  docs/user-guide.rst
  puppet/modules/kubernetes_addons/manifests/tiller.pp
  puppet/modules/kubernetes_addons/templates/tiller-deployment.yaml.erb
Labels: approved, lgtm, release-note, size/M

#343 Upgrade Dashboard and add RBAC support
  docs/user-guide.rst
  puppet/modules/kubernetes_addons/manifests/dashboard.pp
  puppet/modules/kubernetes_addons/spec/classes/dashboard_spec.rb
  puppet/modules/kubernetes_addons/templates/dashboard-deployment.yaml.erb
  puppet/modules/kubernetes_addons/templates/dashboard-rbac.yaml.erb
  puppet/modules/kubernetes_addons/templates/dashboard-svc.yaml.erb
Labels: approved, lgtm, release-note, size/L

#325 Autoscaling arbitrary worker pools
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  pkg/puppet/puppet.go
  pkg/tarmak/instance_pool/instance_pool.go
  puppet/modules/kubernetes_addons/manifests/cluster_autoscaler.pp
  puppet/modules/kubernetes_addons/spec/classes/cluster_autoscaler_spec.rb
  puppet/modules/kubernetes_addons/templates/cluster-autoscaler-deployment.yaml.erb
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/instance_pools.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, release-note, size/M

#336 Remove internal worker ELB
  pkg/tarmak/cluster/roles.go
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
Labels: approved, lgtm, release-note-none, size/XS

#321 Remove Jenkins volume from state module
  terraform/amazon/modules/state/jenkins.tf
  terraform/amazon/modules/state/outputs.tf
Labels: approved, lgtm, release-note, size/S

#367 Upgrade kubernetes versions for testing
  puppet/modules/tarmak/Makefile
Labels: approved, lgtm, release-note-none, size/M

#364 Update vault-helper to 0.9.13
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  pkg/terraform/templating.go
  puppet/modules/vault_client/files/vault-dev-server.service
  puppet/modules/vault_client/manifests/params.pp
  terraform/amazon/templates/vault_instances.tf.template
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_pki_roles.go
Labels: approved, lgtm, priority/P0, release-note, size/L

#369 Add labels & taints option to instance pool config
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/instancepool.go
  pkg/apis/cluster/v1alpha1/label.go
  pkg/apis/cluster/v1alpha1/taint.go
  pkg/puppet/puppet.go
  pkg/tarmak/instance_pool/instance_pool.go
  pkg/tarmak/interfaces/interfaces.go
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/templates/kubelet.service.erb
Labels: approved, lgtm, release-note, size/L

#378 Prepare hub before terraforming other clusters
  pkg/tarmak/cluster/cluster.go
Labels: approved, lgtm, release-note, size/XS

#379 Add note about adding the annotations to all clusters
  docs/existing-vpc.rst
Labels: approved, lgtm, release-note-none, size/XS

#374 Improve AWS validate/verify
  pkg/tarmak/environment/environment.go
  pkg/tarmak/initialize/initialize.go
  pkg/tarmak/provider/amazon/amazon.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/terraform.go
Labels: approved, lgtm, release-note, size/L

#388 Return multierror with ErrorOrNil
  pkg/tarmak/environment/environment.go
Labels: approved, lgtm, release-note-none, size/XS
