Repository jetstack/tarmak, pull requests merged in 2018-06, with the labels that each got.

#275 Ensure terraform destroy runs without refreshing data sources
  pkg/terraform/terraform.go
Labels: approved, lgtm, release-note, size/XS

#285 Refactor validate and verify
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/environment/environment.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/provider/amazon/amazon.go
Labels: approved, lgtm, release-note-none, size/M

#101 Fix existing VPC docs
  docs/existing-vpc.rst
Labels: approved, lgtm, release-note-none, size/XS

#287 Binary compression
  .goreleaser.yml
  Makefile
  hack/minify-binaries.sh
Labels: approved, lgtm, release-note-none, size/M

#293 Add docs for additional IAM policies
  docs/user-guide.rst
Labels: approved, lgtm, release-note-none, size/M

#288 Improve vault tunnel creation
  pkg/tarmak/ssh/tunnel.go
  pkg/tarmak/vault/vault.go
Labels: approved, lgtm, release-note, size/S

#299 Upgrade centos to the latest version 7.3
  puppet/modules/aws_es_proxy/spec/acceptance/nodesets/default.yml
  puppet/modules/calico/spec/acceptance/nodesets/default.yml
  puppet/modules/etcd/spec/acceptance/nodesets/3n-cluster.yml
  puppet/modules/etcd/spec/acceptance/nodesets/default.yml
  puppet/modules/fluent_bit/spec/acceptance/nodesets/default.yml
  puppet/modules/kubernetes/spec/acceptance/nodesets/default.yml
  puppet/modules/tarmak/spec/acceptance/nodesets/default.yml
  puppet/modules/vault_client/spec/acceptance/nodesets/default.yml
Labels: approved, lgtm, release-note-none, size/S

#301 Fix docker slice drop-in
  puppet/modules/site_module/manifests/docker_config.pp
Labels: approved, lgtm, release-note, size/XS

#304 Fix stateful instance naming
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, release-note-none, size/S

#267 264 upgrade cluster autoscaler
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  pkg/puppet/puppet.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/instance_pool/instance_pool.go
  pkg/tarmak/interfaces/interfaces.go
  puppet/hieradata/common.yaml
  puppet/modules/kubernetes_addons/manifests/cluster_autoscaler.pp
  puppet/modules/kubernetes_addons/spec/classes/cluster_autoscaler_spec.rb
  puppet/modules/kubernetes_addons/templates/cluster-autoscaler-deployment.yaml.erb
  puppet/modules/kubernetes_addons/templates/cluster-autoscaler-rbac.yaml.erb
  terraform/amazon/modules/vault/inputs.tf
  terraform/amazon/modules/vault/tls.tf
  terraform/amazon/modules/vault/tls_s3.tf
  terraform/amazon/modules/vault/vault_dns.tf
  terraform/amazon/modules/vault/vault_iam.tf
  terraform/amazon/modules/vault/vault_instances.tf
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, release-note, size/L

#276 Secure endpoints to only allow certain cidr blocks
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/instancepool.go
  pkg/apis/tarmak/v1alpha1/defaults.go
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/environment/environment.go
  pkg/tarmak/instance_pool/instance_pool.go
  pkg/tarmak/interfaces/interfaces.go
  terraform/amazon/modules/bastion/bastion.tf
  terraform/amazon/modules/bastion/inputs.tf
  terraform/amazon/modules/jenkins/inputs.tf
  terraform/amazon/modules/kubernetes/inputs.tf
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/role_security_group.tf.template
  terraform/amazon/templates/jenkins_elb.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, release-note, size/L

#305 Fix sphinx docs
  docs/Dockerfile
  docs/Makefile
  docs/requirements.txt
Labels: approved, lgtm, release-note, size/S

#292 Enable secrets and configMaps encryption in etcd rest on the apiserver
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/manifests/init.pp
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
  puppet/modules/tarmak/manifests/master.pp
  puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
  puppet/modules/tarmak/spec/spec_helper_acceptance.rb
  puppet/modules/vault_client/files/vault-add-hostname.sh
  puppet/modules/vault_client/files/vault-dev-server.service
  puppet/modules/vault_client/files/vault-dev-server.sh
  puppet/modules/vault_client/manifests/params.pp
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/generic.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/generic_vault_backend.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/init_token.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_pki_roles.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_policies.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/pki_vault_backend.go
Labels: approved, lgtm, release-note, size/XXL

#306 Cluster and instance pool section should within IAM additional chapter
  docs/user-guide.rst
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#326 Fix errors when failing to parse config
  pkg/tarmak/config/config.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/kubectl/kubectl.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/tarmak_test.go
Labels: approved, lgtm, release-note, size/M

#323 Upgrade terraform to 0.11.7
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go
  vendor/github.com/hashicorp/terraform/terraform/interpolate.go
  vendor/github.com/hashicorp/terraform/version/version.go
Labels: approved, lgtm, release-note, size/M

#322 Pass through etcd instance pool min count to puppet
  pkg/puppet/puppet.go
  puppet/hieradata/common.yaml
Labels: approved, lgtm, release-note, size/XS

#319 Use ClusterFirstWithHostNet for fluent-bit daemon set
  puppet/modules/fluent_bit/templates/fluent-bit-daemonset.yaml.erb
Labels: approved, lgtm, release-note, size/XS

#330 Fix duplicate ELB name error
  terraform/amazon/templates/instance_pools/role_elb.tf.template
Labels: approved, lgtm, release-note, size/XS

#327 Docs for API Server
  docs/user-guide.rst
Labels: approved, lgtm, release-note-none, size/S

#329 Remove unneeded input for Jenkins instance size
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, release-note, size/XS

#346 Use latest versions of Cluster Autoscaler
  puppet/modules/kubernetes_addons/manifests/cluster_autoscaler.pp
  puppet/modules/kubernetes_addons/spec/classes/cluster_autoscaler_spec.rb
Labels: approved, lgtm, release-note, size/S

#338 Add security group to allow cluster autoscaler scraping
  pkg/tarmak/cluster/firewall/rules.go
Labels: approved, lgtm, release-note-none, size/M

#309 Support overprovisioning
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/puppet/puppet.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/cluster/cluster_test.go
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/manifests/init.pp
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/manifests/scheduler.pp
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
  puppet/modules/kubernetes/templates/kube-scheduler.service.erb
  puppet/modules/kubernetes/templates/kubelet.service.erb
  puppet/modules/kubernetes_addons/manifests/cluster_autoscaler.pp
  puppet/modules/kubernetes_addons/spec/classes/cluster_autoscaler_spec.rb
  puppet/modules/kubernetes_addons/templates/cluster-autoscaler-deployment.yaml.erb
  puppet/modules/kubernetes_addons/templates/cluster-autoscaler-overprovisioning-rbac.yaml.erb
  puppet/modules/kubernetes_addons/templates/cluster-autoscaler-overprovisioning.yaml.erb
Labels: approved, lgtm, release-note, size/XL

#300 Change cgroup driver from systemd to cgroupfs
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/acceptance/single_node_spec.rb
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/site_module/files/20-cgroupfs.conf
  puppet/modules/site_module/manifests/docker.pp
  puppet/modules/site_module/manifests/docker_config.pp
  puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
Labels: approved, lgtm, release-note, size/M

#350 Create an SRV record for the etcd instance pool
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
Labels: approved, lgtm, release-note, size/S

#296 Support hard and soft evictions
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/templates/kubelet.service.erb
Labels: approved, lgtm, release-note, size/L
