Repository jetstack/tarmak, pull requests merged in 2018-04, with the labels that each got.

#140 Add proposal for a custom vault auth provider
  docs/proposals/vault-auth-provider.rst
  docs/spelling_wordlist.txt
Labels: approved, lgtm, release-note-none, size/L

#161 Fix docker html container
  docs/Dockerfile
  docs/Makefile
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#150 Set kubelet eviction-hard based on total memory
  puppet/modules/kubernetes/lib/puppet/functions/five_percent_of_total_ram.rb
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/spec/spec_helper.rb
  puppet/modules/kubernetes/templates/kubelet.service.erb
Labels: approved, lgtm, release-note, size/S

#165 Current cluster flags
  cmd/tarmak/cmd/cluster_list.go
  cmd/tarmak/cmd/root.go
  pkg/apis/tarmak/v1alpha1/types.go
  pkg/tarmak/config/config.go
  pkg/tarmak/config/config_test.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/kubectl/kubectl.go
  pkg/tarmak/tarmak.go
Labels: approved, lgtm, release-note, size/M

#175 Make log method private
  pkg/terraform/providers/tarmak/rpc/rpc.go
Labels: approved, lgtm, release-note-none, size/S

#177 Add support for building tarmak using Jenkins
  .gitlab-ci.yml
  Makefile
  hack/jenkins/Jenkinsfile.tarmak_build
Labels: approved, lgtm, release-note, size/M

#181 Update vault-helper to 0.9.9
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/generic.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/init_token.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_pki_roles.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_policies.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/pki.go
  vendor/github.com/jetstack/vault-helper/pkg/kubernetes/policy.go
Labels: approved, lgtm, release-note, size/S

#188 Return tarmak cluster plan error code
  pkg/tarmak/cluster/configuration.go
  pkg/tarmak/utils/context.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, release-note, size/S

#194 Expand relative config directory arguments
  pkg/tarmak/tarmak.go
Labels: approved, lgtm, release-note, size/XS

#166 Expose OIDC api server options
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/puppet/puppet.go
  pkg/puppet/puppet_test.go
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/role/role.go
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
  puppet/modules/tarmak/manifests/master.pp
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/instance_pools/role_elb.tf.template
  terraform/amazon/templates/instance_pools/role_security_group.tf.template
Labels: approved, lgtm, release-note, size/L

#196 Archive darwin artifact in Jenkins build
  hack/jenkins/Jenkinsfile.tarmak_build
Labels: approved, lgtm, release-note-none
