Repository jetstack/tarmak, pull requests merged in 2018-08, with the labels that each got.

#397 Fix failing terraform destroy
  terraform/amazon/modules/state/outputs.tf
Labels: approved, cherrypick-approved, lgtm, release-note-none, size/XS

#398 Automated cherry pick of #397
  terraform/amazon/modules/state/outputs.tf
Labels: approved, lgtm, release-note-none, size/XS

#399 Automated cherry pick of #369
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/instancepool.go
  pkg/apis/cluster/v1alpha1/label.go
  pkg/apis/cluster/v1alpha1/taint.go
  pkg/puppet/puppet.go
  pkg/tarmak/instance_pool/instance_pool.go
  pkg/tarmak/interfaces/interfaces.go
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/templates/kubelet.service.erb
Labels: approved, lgtm, release-note-none, size/L

#401 Add docs for set-context
  docs/design_cli_ux.rst
Labels: approved, lgtm, release-note-none, size/S

#387 Recreate wing instances when absent
  pkg/wing/controller.go
Labels: approved, cherrypick-approved, lgtm, release-note, size/S

#402 Relax Label and Taint validations
  Gopkg.lock
  pkg/tarmak/instance_pool/instance_pool.go
  pkg/tarmak/instance_pool/instance_pool_test.go
Labels: approved, cherrypick-approved, lgtm, release-note, size/L

#407 Fix logging documentation
  docs/user-guide.rst
Labels: approved, lgtm, release-note-none, size/M

#409 Tolerate dedicated on calico, node-exporter & fluent-bit
  puppet/modules/calico/templates/node-daemonset.yaml.erb
  puppet/modules/fluent_bit/templates/fluent-bit-daemonset.yaml.erb
  puppet/modules/prometheus/templates/node-exporter-ds.yaml.erb
Labels: approved, lgtm, release-note, size/XS

#408 Use TLS by default for logging sinks
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/cluster/v1alpha1/defaults_test.go
  pkg/apis/cluster/v1alpha1/logging.go
Labels: approved, lgtm, release-note, size/M

#386 Fix audit max backups and log location
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Labels: approved, lgtm, release-note, size/S

#412 Automated cherry pick of #185 #319 #386 #387 #408
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/cluster/v1alpha1/defaults_test.go
  pkg/apis/cluster/v1alpha1/logging.go
  pkg/wing/controller.go
  puppet/modules/fluent_bit/templates/fluent-bit-daemonset.yaml.erb
  puppet/modules/kubernetes/manifests/apiserver.pp
  puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Labels: approved, lgtm, release-note, size/L

#417 Fix typo in struct annotations for Labels
  pkg/apis/cluster/v1alpha1/instancepool.go
Labels: approved, lgtm, release-note-none, size/XS

#418 Automated cherry pick of #407 #414
  docs/user-guide.rst
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/cluster/v1alpha1/instancepool.go
  puppet/modules/tarmak/Makefile
  puppet/modules/tarmak/manifests/master.pp
  puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
Labels: approved, lgtm, release-note-none, size/L

#460 Change root url for Grafana
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  puppet/modules/kubernetes_addons/templates/grafana-deployment.yaml.erb
Labels: approved, lgtm, release-note, size/S

#447 Expose root volume sizes as tfvars
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/interfaces/interfaces.go
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, release-note, size/S

#465 Automated cherry pick of #447
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/interfaces/interfaces.go
  terraform/amazon/templates/inputs.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template
  terraform/amazon/templates/modules.tf.template
Labels: approved, lgtm, size/S

#464 Automated cherry pick of #460
  docs/spelling_wordlist.txt
  docs/user-guide.rst
  puppet/modules/kubernetes_addons/templates/grafana-deployment.yaml.erb
Labels: approved, lgtm, size/S

#473 Consul puppet module
  puppet/modules/airworthy/manifests/init.pp
  puppet/modules/airworthy/manifests/install.pp
  puppet/modules/consul/.fixtures.yml
  puppet/modules/consul/.fixtures.yml.local
  puppet/modules/consul/.gitignore
  puppet/modules/consul/Gemfile.lock
  puppet/modules/consul/Makefile
  puppet/modules/consul/Rakefile
  puppet/modules/consul/files/consul-backup.sh
  puppet/modules/consul/lib/puppet/parser/functions/get_ipaddress_in_network.rb
  puppet/modules/consul/manifests/config.pp
  puppet/modules/consul/manifests/init.pp
  puppet/modules/consul/manifests/install.pp
  puppet/modules/consul/manifests/params.pp
  puppet/modules/consul/manifests/service.pp
  puppet/modules/consul/spec/acceptance/nodesets/3n-cluster.yml
  puppet/modules/consul/spec/acceptance/nodesets/default.yml
  puppet/modules/consul/spec/acceptance/nodesets/ubuntu_1604_single_node.yml
  puppet/modules/consul/spec/acceptance/single_node_spec.rb
  puppet/modules/consul/spec/acceptance/three_nodes_spec.rb
  puppet/modules/consul/spec/classes/config_spec.rb
  puppet/modules/consul/spec/classes/init_spec.rb
  puppet/modules/consul/spec/classes/install_spec.rb
  puppet/modules/consul/spec/classes/service_spec.rb
  puppet/modules/consul/spec/functions/get_ipadress_in_netowrk_spec.rb
  puppet/modules/consul/spec/spec_helper.rb
  puppet/modules/consul/spec/spec_helper_acceptance.rb
  puppet/modules/consul/templates/consul-backup.service.erb
  puppet/modules/consul/templates/consul-backup.timer.erb
  puppet/modules/consul/templates/consul-exporter.service.erb
  puppet/modules/consul/templates/consul.json.erp
  puppet/modules/consul/templates/consul.service.erb
Labels: approved, lgtm, release-note-none, size/XXL
