Repository jetstack/tarmak, pull requests merged in 2019-03, with the labels that each got.

#758 Revert "Upgrade UPX to 3.95"
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#759 Automated cherry pick of #758
  Makefile
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#763 Fix Terraform bug
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/hashicorp/terraform/terraform/eval_diff.go
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, release-note, size/S

#768 Change the depends_on to the resource
  terraform/amazon/templates/vault_instances.tf.template
Labels: approved, area/terraform, dco-signoff: yes, lgtm, release-note, size/XS

#766 Detect existing datacenter
  puppet/hieradata/common.yaml
  puppet/modules/consul/files/consul-detect-existing-datacenter.sh
  puppet/modules/consul/manifests/install.pp
  puppet/modules/consul/manifests/service.pp
  puppet/modules/consul/templates/consul.service.erb
Labels: approved, area/puppet, dco-signoff: yes, lgtm, release-note, size/S

#767 Mount filesystems regardless of type
  puppet/modules/aws_ebs/manifests/mount.pp
  puppet/modules/aws_ebs/spec/defines/mount_spec.rb
  puppet/modules/aws_ebs/templates/ensure-volume-formatted.service.erb
  puppet/modules/aws_ebs/templates/ensure_volume_formatted.sh.erb
  puppet/modules/aws_ebs/templates/volume.mount.erb
Labels: approved, area/puppet, dco-signoff: yes, lgtm, release-note, size/S

#769 Automated cherry pick of #766 #767 #768
  puppet/hieradata/common.yaml
  puppet/modules/aws_ebs/manifests/mount.pp
  puppet/modules/aws_ebs/spec/defines/mount_spec.rb
  puppet/modules/aws_ebs/templates/ensure-volume-formatted.service.erb
  puppet/modules/aws_ebs/templates/ensure_volume_formatted.sh.erb
  puppet/modules/aws_ebs/templates/volume.mount.erb
  puppet/modules/consul/files/consul-detect-existing-datacenter.sh
  puppet/modules/consul/manifests/install.pp
  puppet/modules/consul/manifests/service.pp
  puppet/modules/consul/templates/consul.service.erb
  terraform/amazon/templates/vault_instances.tf.template
Labels: approved, area/puppet, area/terraform, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#764 Automated cherry pick of #763
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/hashicorp/terraform/terraform/eval_diff.go
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#775 Backport fixes from network into network-existing-vpc
  terraform/amazon/modules/network-existing-vpc/outputs.tf
Labels: approved, area/terraform, dco-signoff: yes, lgtm, release-note, size/XS

#776 Automated cherry pick of #775
  terraform/amazon/modules/network-existing-vpc/outputs.tf
Labels: approved, area/terraform, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#773 Replace EnsureDirectoryExists by os.MkdirAll
  pkg/puppet/puppet.go
  pkg/tarmak/config/config.go
  pkg/tarmak/environment/environment.go
  pkg/tarmak/kubectl/kubectl.go
  pkg/tarmak/ssh/ssh.go
  pkg/tarmak/utils/files.go
  pkg/tarmak/vault/vault.go
  pkg/terraform/templating.go
  pkg/terraform/terraform.go
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, release-note, size/M

#774 Automated cherry pick of #773
  pkg/puppet/puppet.go
  pkg/tarmak/config/config.go
  pkg/tarmak/environment/environment.go
  pkg/tarmak/kubectl/kubectl.go
  pkg/tarmak/ssh/ssh.go
  pkg/tarmak/utils/files.go
  pkg/tarmak/vault/vault.go
  pkg/terraform/templating.go
  pkg/terraform/terraform.go
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#777 Improve usability of existing VPC for testing
  docs/existing-vpc.rst
  docs/existing-vpc/vpc.tf
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#779 Don't close closed channel in tunnel
  pkg/tarmak/ssh/tunnel.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#778 Ensure known hosts path is the same as ssh_config
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/ssh/ssh.go
  pkg/tarmak/tarmak.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#780 Automated cherry pick of #775
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/ssh/ssh.go
  pkg/tarmak/tarmak.go
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#781 Automated cherry pick of #779
  pkg/tarmak/ssh/tunnel.go
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#784 Disable sctp
  packer/amazon/configure_for_tarmak.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#785 Automated cherry pick of #784
  packer/amazon/configure_for_tarmak.sh
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#786 Upgrade default Kubernetes version to 1.12.6
  CHANGELOG.md
  pkg/apis/cluster/v1alpha1/defaults.go
  puppet/modules/tarmak/Makefile
Labels: approved, area/puppet, dco-signoff: yes, lgtm, release-note, size/S

#787 Automated cherry pick of #786
  CHANGELOG.md
  pkg/apis/cluster/v1alpha1/defaults.go
  puppet/modules/tarmak/Makefile
Labels: approved, area/puppet, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#788 Upgrade default Kubernetes version to 1.12.7
  CHANGELOG.md
  pkg/apis/cluster/v1alpha1/defaults.go
  puppet/modules/tarmak/Makefile
Labels: approved, area/puppet, dco-signoff: yes, lgtm, release-note, size/S

#789 Automated cherry pick of #788
  CHANGELOG.md
  pkg/apis/cluster/v1alpha1/defaults.go
  puppet/modules/tarmak/Makefile
Labels: approved, area/puppet, cherry-pick-approved, dco-signoff: yes, lgtm, size/S
