Repository jetstack/tarmak, pull requests merged in 2019-01, with the labels that each got.

#674 Upgrade vault to 0.9.6 and consul to 1.2.4
  CHANGELOG.md
  Gopkg.toml
  puppet/modules/consul/manifests/params.pp
  puppet/modules/consul/spec/classes/install_spec.rb
  puppet/modules/vault_client/files/vault-dev-server.service
  puppet/modules/vault_server/manifests/params.pp
  puppet/modules/vault_server/spec/classes/install_spec.rb
  terraform/amazon/templates/inputs.tf.template
Labels: approved, area/puppet, area/terraform, dco-signoff: yes, lgtm, release-note, size/S

#678 Enables wing-dev-mode on bastion instances
  pkg/tarmak/cluster/cluster.go
  pkg/terraform/templating.go
  terraform/amazon/modules/bastion/bastion.tf
  terraform/amazon/modules/bastion/bastion_iam.tf
  terraform/amazon/modules/bastion/inputs.tf
  terraform/amazon/modules/bastion/outputs.tf
  terraform/amazon/modules/bastion/templates/wing_binary_read.json
  terraform/amazon/modules/jenkins/inputs.tf
  terraform/amazon/modules/kubernetes/iam_policies.tf
  terraform/amazon/modules/kubernetes/inputs.tf
  terraform/amazon/modules/kubernetes/templates/iam_tarmak_bucket_read.json
  terraform/amazon/modules/vault/inputs.tf
  terraform/amazon/modules/vault/templates/iam_tarmak_bucket_read.json
  terraform/amazon/modules/vault/vault_iam.tf
  terraform/amazon/templates/bastion_user_data.yaml.template
  terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template
  terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
  terraform/amazon/templates/modules.tf.template
  terraform/amazon/templates/outputs.tf.template
  terraform/amazon/templates/wing_s3.tf.template
Labels: approved, area/terraform, dco-signoff: yes, lgtm, release-note, size/L

#680 Upgrade to golang version 1.11.4
  .gitlab-ci.yml
  Makefile
  pkg/packer/image.go
  pkg/tarmak/provider/amazon/tf_remote_state.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#390 Add separate Packer builder for Kubernetes workers
  Gopkg.lock
  packer/amazon/centos-puppet-agent-k8s-worker.json
  packer/amazon/prepare_puppet.sh
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/apis/tarmak/v1alpha1/constants.go
  pkg/packer/image.go
  pkg/packer/packer.go
  pkg/puppet/puppet.go
  pkg/tarmak/interfaces/interfaces.go
  puppet/modules/kubernetes/manifests/kubelet.pp
  puppet/modules/kubernetes/manifests/proxy.pp
  puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
  puppet/modules/kubernetes/spec/classes/proxy_spec.rb
  puppet/modules/tarmak/manifests/init.pp
  puppet/modules/tarmak/manifests/overlay_calico.pp
  puppet/modules/tarmak/manifests/worker.pp
  puppet/modules/tarmak/spec/acceptance/cluster_packer_spec.rb
  puppet/modules/tarmak/spec/classes/overlay_calico_spec.rb
  puppet/modules/tarmak/spec/classes/worker_spec.rb
  puppet/modules/vault_client/manifests/cert_service.pp
  puppet/modules/vault_client/manifests/config.pp
  puppet/modules/vault_client/manifests/init.pp
  puppet/modules/vault_client/manifests/params.pp
  puppet/modules/vault_client/manifests/service.pp
  puppet/modules/vault_client/spec/acceptance/standard_spec.rb
  puppet/modules/vault_client/spec/classes/init_spec.rb
  puppet/modules/vault_client/spec/defines/cert_service_spec.rb
  vendor/github.com/hashicorp/packer/provisioner/file/provisioner.go
  vendor/github.com/hashicorp/packer/provisioner/guest_commands.go
  vendor/github.com/hashicorp/packer/provisioner/puppet-masterless/provisioner.go
Labels: approved, area/puppet, dco-signoff: yes, kind/documentation, lgtm, release-note, size/XXL

#698 Ensure volumes are correctly mounted for vault instances
  puppet/hieradata/role/vault.yaml
  puppet/modules/consul/manifests/service.pp
  puppet/modules/tarmak/manifests/vault.pp
  puppet/modules/tarmak/spec/classes/vault_spec.rb
  puppet/modules/tarmak/spec/spec_helper.rb
  puppet/modules/vault_server/manifests/init.pp
  terraform/amazon/modules/vault/templates/vault_role_policy.json
Labels: approved, area/puppet, area/terraform, dco-signoff: yes, lgtm, release-note-none, size/M

#701 Fix signature spelling
  pkg/tagging_control/tagging_control.go
  pkg/tagging_control/tagging_control_test.go
  pkg/wing/tags/aws/aws.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#703 Ensure cluster directory before creating known_hosts file
  pkg/tarmak/ssh/ssh.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#704 Use kubernetes upstream version scripts
  Makefile
  cmd/tagging_control/cmd/version.go
  cmd/tarmak/cmd/version.go
  cmd/wing/cmd/version.go
  docs/generated/cmd/tagging_control/tagging_control.rst
  docs/generated/cmd/tagging_control/tagging_control_version.rst
  docs/generated/cmd/wing/wing.rst
  docs/generated/cmd/wing/wing_version.rst
  hack/lib/version.sh
  hack/print-workspace-status.sh
  hack/update-cmd-docs.sh
  hack/version-ldflags.sh
  pkg/version/.gitattributes
  pkg/version/base.go
  pkg/version/doc.go
  pkg/version/version.go
  pkg/wing/apiserver/apiserver.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#705 Separate binaries and assets
  cmd/tagging_control/cmd/zip.go
  docs/cmd-docs.rst
  docs/generated/cmd/tagging_control/tagging_control.rst
  docs/generated/cmd/tagging_control/tagging_control_zip.rst
  pkg/tarmak/assets/assets.go
  pkg/tarmak/assets/assets_dev.go
  pkg/tarmak/binaries/.gitignore
  pkg/tarmak/binaries/binaries.go
  pkg/tarmak/binaries/binaries_dev.go
  pkg/tarmak/utils/zip/zip.go
  pkg/tarmak/utils/zip/zip_test.go
  pkg/terraform/templating.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#707 Remove VPC endpoints from being created in existing VPC
  docs/existing-vpc.rst
  terraform/amazon/modules/network-existing-vpc/route53.tf
  terraform/amazon/modules/network-existing-vpc/vpc_endpoints.tf
Labels: approved, area/terraform, dco-signoff: yes, kind/documentation, lgtm, release-note, size/S

#657 Add Heptio Ark example in docs
  docs/examples/ark.rst
  docs/spelling_wordlist.txt
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note, size/M

#635 Replace exec with pkg ssh
  cmd/tarmak/cmd/cluster_instances_ssh.go
  cmd/tarmak/cmd/cluster_ssh.go
  cmd/tarmak/cmd/tunnel.go
  docs/cmd-docs.rst
  docs/generated/cmd/tarmak/tarmak_clusters_instances_ssh.rst
  docs/generated/cmd/tarmak/tarmak_clusters_ssh.rst
  pkg/tarmak/cluster/cluster.go
  pkg/tarmak/cluster/cluster_test.go
  pkg/tarmak/cluster/configuration.go
  pkg/tarmak/environment/bastion.go
  pkg/tarmak/environment/environment.go
  pkg/tarmak/interfaces/interfaces.go
  pkg/tarmak/kubectl/kubectl.go
  pkg/tarmak/provider/amazon/hosts.go
  pkg/tarmak/ssh.go
  pkg/tarmak/ssh/ssh.go
  pkg/tarmak/ssh/tunnel.go
  pkg/tarmak/tarmak.go
  pkg/tarmak/utils/context.go
  pkg/tarmak/vault/tunnel.go
  pkg/tarmak/vault/tunnel_test.go
  pkg/tarmak/vault/vault.go
Labels: approved, area/terraform, dco-signoff: yes, kind/documentation, lgtm, release-note, size/XXL

#710 Stop warning about failed bastion conn and forget
  pkg/tarmak/ssh/ssh.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#694 Extend docs for Pod Security Policy
  docs/user-guide.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#693 Fix tiller docs
  docs/user-guide.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#713 Use correct path to package
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#714 Remove goreleaser remains
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#712 Use custom metrics server image for API proxy
  puppet/modules/kubernetes_addons/manifests/metrics_server.pp
  puppet/modules/kubernetes_addons/templates/metrics-server-rbac.yaml.erb
  puppet/modules/kubernetes_addons/templates/metrics-server.yaml.erb
Labels: approved, area/puppet, dco-signoff: yes, lgtm, release-note, size/XS
